/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/wechat/h5/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * H5微信登录
         * @description 微信公众号网页授权登录，用 code 换取 JWT
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description 登录成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"] & {
                            data?: components["schemas"]["LoginResponse"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/wechat/mp/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 小程序微信登录
         * @description 微信小程序登录，用 wx.login code 换取 JWT
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description 登录成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"] & {
                            data?: components["schemas"]["LoginResponse"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 刷新Token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RefreshRequest"];
                };
            };
            responses: {
                /** @description 刷新成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"] & {
                            data?: components["schemas"]["RefreshResponse"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取当前用户信息 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 用户信息 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"] & {
                            data?: components["schemas"]["UserProfile"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 更新个人资料 */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        nickname?: string;
                        avatarUrl?: string;
                    };
                };
            };
            responses: {
                /** @description 更新成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"] & {
                            data?: components["schemas"]["UserBrief"];
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/users/me/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取提醒设置
         * @description 获取当前用户在各家庭下的提醒开关状态
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 提醒设置列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"] & {
                            data?: components["schemas"]["UserSettings"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 更新提醒设置
         * @description 更新当前用户在指定家庭下的提醒开关
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateUserSettingsRequest"];
                };
            };
            responses: {
                /** @description 更新成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"] & {
                            data?: {
                                /** Format: uuid */
                                familyId?: string;
                                reminderEnabled?: boolean;
                            };
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/families": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 我的家庭列表 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 家庭列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"] & {
                            data?: components["schemas"]["FamilyWithRole"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** 创建家庭 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateFamilyRequest"];
                };
            };
            responses: {
                /** @description 创建成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"] & {
                            data?: components["schemas"]["FamilyDetail"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/families/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 通过邀请码加入家庭 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["JoinFamilyRequest"];
                };
            };
            responses: {
                /** @description 加入成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"] & {
                            data?: components["schemas"]["JoinFamilyResponse"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/families/{familyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 家庭详情 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    familyId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 家庭详情 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"] & {
                            data?: components["schemas"]["FamilyDetail"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/families/{familyId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 家庭成员列表 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    familyId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成员列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"] & {
                            data?: components["schemas"]["MemberDetail"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/families/{familyId}/tasks/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 家庭任务统计
         * @description 获取每个成员的当前待办数和本周完成数（轻量公平感）
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    familyId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 统计数据 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"] & {
                            data?: components["schemas"]["FamilyStatsResponse"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/families/{familyId}/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 生成邀请码 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    familyId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 邀请码 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"] & {
                            data?: components["schemas"]["InvitationResponse"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/families/{familyId}/members/{memberId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 移除家庭成员 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    familyId: string;
                    memberId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 移除成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/families/{familyId}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 任务列表
         * @description 支持按状态、执行人、逾期/临近到期筛选 + 分页
         */
        get: {
            parameters: {
                query?: {
                    status?: "PENDING_COMPLETION" | "PENDING_VERIFICATION" | "REJECTED" | "COMPLETED" | "CANCELLED";
                    /** @description 筛选已逾期任务 */
                    overdue?: boolean;
                    /** @description 筛选临近到期任务 */
                    nearExpiry?: boolean;
                    assignedTo?: string;
                    page?: number;
                    pageSize?: number;
                };
                header?: never;
                path: {
                    familyId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 任务列表（分页） */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"] & {
                            data?: components["schemas"]["PaginatedData"] & {
                                items?: components["schemas"]["TaskListItem"][];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        /**
         * 创建任务
         * @description ORGANIZER 或 MEMBER 可创建；CHILD 默认不可创建
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    familyId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateTaskRequest"];
                };
            };
            responses: {
                /** @description 创建成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"] & {
                            data?: components["schemas"]["TaskDetail"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/families/{familyId}/tasks/{taskId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 任务详情 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    familyId: string;
                    taskId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 任务详情 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"] & {
                            data?: components["schemas"]["TaskDetail"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 编辑任务
         * @description 仅 ORGANIZER 可编辑
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    familyId: string;
                    taskId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateTaskRequest"];
                };
            };
            responses: {
                /** @description 编辑成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"] & {
                            data?: components["schemas"]["TaskDetail"];
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/families/{familyId}/tasks/{taskId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 标记任务完成
         * @description 执行人标记任务完成，可附带备注和照片URL。无需验收的任务直接进入COMPLETED，需要验收的进入PENDING_VERIFICATION。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    familyId: string;
                    taskId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CompleteTaskRequest"];
                };
            };
            responses: {
                /** @description 标记完成 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"] & {
                            data?: {
                                /** Format: uuid */
                                id?: string;
                                /**
                                 * @description needsVerification=false→COMPLETED, true→PENDING_VERIFICATION
                                 * @enum {string}
                                 */
                                status?: "COMPLETED" | "PENDING_VERIFICATION";
                                /** Format: date-time */
                                completedAt?: string;
                                completionNote?: string | null;
                                completionPhoto?: string | null;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/families/{familyId}/tasks/{taskId}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 验收通过
         * @description 仅 ORGANIZER 可操作
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    familyId: string;
                    taskId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 验收通过 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"] & {
                            data?: {
                                /** Format: uuid */
                                id?: string;
                                /** @example COMPLETED */
                                status?: string;
                                /** Format: date-time */
                                verifiedAt?: string;
                                verifiedBy?: components["schemas"]["UserBrief"];
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/families/{familyId}/tasks/{taskId}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 驳回任务
         * @description 仅 ORGANIZER 可操作，驳回原因必填，任务进入 REJECTED 状态
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    familyId: string;
                    taskId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RejectTaskRequest"];
                };
            };
            responses: {
                /** @description 已驳回 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"] & {
                            data?: {
                                /** Format: uuid */
                                id?: string;
                                /** @example REJECTED */
                                status?: string;
                                rejectionReason?: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/families/{familyId}/tasks/{taskId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 取消任务
         * @description ORGANIZER 可取消任何任务，MEMBER 仅可取消自己创建的任务
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    familyId: string;
                    taskId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CancelTaskRequest"];
                };
            };
            responses: {
                /** @description 已取消 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"] & {
                            data?: {
                                /** Format: uuid */
                                id?: string;
                                /** @example CANCELLED */
                                status?: string;
                                /** Format: date-time */
                                cancelledAt?: string;
                                cancelledReason?: string | null;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/task-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取任务模板列表
         * @description 获取内置任务模板，用于快速创建常见家务任务
         */
        get: {
            parameters: {
                query?: {
                    /** @description 按分类筛选（可选） */
                    category?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 模板列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"] & {
                            data?: {
                                templates?: components["schemas"]["TaskTemplateItem"][];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/upload/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 上传图片 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /**
                         * Format: binary
                         * @description 图片文件（jpg/png/webp，最大5MB）
                         */
                        file: string;
                    };
                };
            };
            responses: {
                /** @description 上传成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"] & {
                            data?: components["schemas"]["UploadResponse"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SuccessResponse: {
            /** @example 0 */
            code?: number;
            /** @example ok */
            message?: string;
            data?: Record<string, never>;
        };
        ErrorResponse: {
            /** @example 40001 */
            code?: number;
            /** @example 错误描述 */
            message?: string;
            /** @example 详细错误信息 */
            detail?: string;
        };
        PaginatedData: {
            items?: unknown[];
            /** @example 100 */
            total?: number;
            /** @example 1 */
            page?: number;
            /** @example 20 */
            pageSize?: number;
        };
        UserBrief: {
            /** Format: uuid */
            id?: string;
            /** @example 小明妈妈 */
            nickname?: string;
            /** @example https://... */
            avatarUrl?: string | null;
        };
        UserProfile: components["schemas"]["UserBrief"] & {
            families?: {
                /** Format: uuid */
                id?: string;
                name?: string;
                /** @enum {string} */
                role?: "ORGANIZER" | "MEMBER" | "CHILD";
            }[];
        };
        LoginRequest: {
            /** @description 微信 OAuth code 或 wx.login code */
            code: string;
        };
        LoginResponse: {
            /** @example eyJhbG... */
            accessToken?: string;
            /** @example eyJhbG... */
            refreshToken?: string;
            /** @example 7200 */
            expiresIn?: number;
            user?: components["schemas"]["UserBrief"];
        };
        RefreshRequest: {
            refreshToken: string;
        };
        RefreshResponse: {
            accessToken?: string;
            expiresIn?: number;
        };
        UserSettings: {
            settings?: {
                /** Format: uuid */
                familyId?: string;
                familyName?: string;
                reminderEnabled?: boolean;
            }[];
        };
        UpdateUserSettingsRequest: {
            /** Format: uuid */
            familyId: string;
            reminderEnabled: boolean;
        };
        CreateFamilyRequest: {
            /** @example 幸福三口之家 */
            name: string;
        };
        FamilyDetail: {
            /** Format: uuid */
            id?: string;
            name?: string;
            /** @example ABC123 */
            inviteCode?: string;
            /** Format: uuid */
            createdBy?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        FamilyWithRole: components["schemas"]["FamilyDetail"] & {
            /** @enum {string} */
            role?: "ORGANIZER" | "MEMBER" | "CHILD";
            /** @example 3 */
            memberCount?: number;
        };
        MemberDetail: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            userId?: string;
            nickname?: string;
            avatarUrl?: string | null;
            /** @enum {string} */
            role?: "ORGANIZER" | "MEMBER" | "CHILD";
            /** @example true */
            reminderEnabled?: boolean;
            /** Format: date-time */
            joinedAt?: string;
        };
        InvitationResponse: {
            /** Format: uuid */
            id?: string;
            /** @example XYZ789 */
            code?: string;
            /** Format: date-time */
            expiresAt?: string;
            /** @example https://your-domain.com/invite?code=XYZ789 */
            inviteUrl?: string;
        };
        JoinFamilyRequest: {
            /** @example XYZ789 */
            code: string;
        };
        JoinFamilyResponse: {
            /** Format: uuid */
            familyId?: string;
            familyName?: string;
            /** @enum {string} */
            role?: "MEMBER";
        };
        FamilyStatsResponse: {
            members?: {
                /** Format: uuid */
                userId?: string;
                nickname?: string;
                avatarUrl?: string | null;
                /** @example 2 */
                pendingCount?: number;
                /** @example 5 */
                weeklyCompletedCount?: number;
            }[];
        };
        CreateTaskRequest: {
            /** @example 今天洗碗 */
            title: string;
            /** @example 用洗洁精认真洗 */
            description?: string | null;
            /** @default 1 */
            difficulty: number;
            /**
             * Format: date-time
             * @example 2026-06-10T20:00:00Z
             */
            deadline: string;
            /**
             * Format: uuid
             * @description 执行人用户ID（必填，v1.1不再支持待分配）
             */
            assignedTo: string;
            /**
             * @description 重复规则
             * @default NONE
             * @enum {string}
             */
            repeatRule: "NONE" | "DAILY" | "WEEKLY";
            /**
             * @description 是否需要组织者验收
             * @default false
             */
            needsVerification: boolean;
        };
        UpdateTaskRequest: {
            title?: string;
            description?: string | null;
            difficulty?: number;
            /** Format: date-time */
            deadline?: string;
            /** Format: uuid */
            assignedTo?: string;
            /** @enum {string} */
            repeatRule?: "NONE" | "DAILY" | "WEEKLY";
            needsVerification?: boolean;
        };
        CompleteTaskRequest: {
            /** @description 完成备注（可选） */
            completionNote?: string | null;
            /** @description 完成照片URL（可选，先通过 POST /api/upload/image 获取） */
            completionPhoto?: string | null;
        };
        TaskDetail: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            familyId?: string;
            title?: string;
            description?: string | null;
            difficulty?: number;
            /** Format: date-time */
            deadline?: string;
            /** @enum {string} */
            status?: "PENDING_COMPLETION" | "PENDING_VERIFICATION" | "REJECTED" | "COMPLETED" | "CANCELLED";
            /** @enum {string} */
            repeatRule?: "NONE" | "DAILY" | "WEEKLY";
            needsVerification?: boolean;
            assignedTo?: components["schemas"]["UserBrief"];
            createdBy?: components["schemas"]["UserBrief"];
            completionNote?: string | null;
            completionPhoto?: string | null;
            /** Format: date-time */
            completedAt?: string | null;
            /** Format: date-time */
            verifiedAt?: string | null;
            verifiedBy?: components["schemas"]["UserBrief"];
            rejectionReason?: string | null;
            /** Format: date-time */
            cancelledAt?: string | null;
            cancelledBy?: components["schemas"]["UserBrief"];
            cancelledReason?: string | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        TaskListItem: {
            /** Format: uuid */
            id?: string;
            title?: string;
            difficulty?: number;
            /** Format: date-time */
            deadline?: string;
            status?: string;
            /** @enum {string} */
            repeatRule?: "NONE" | "DAILY" | "WEEKLY";
            needsVerification?: boolean;
            /** @description 计算状态：是否已逾期 */
            isOverdue?: boolean;
            /** @description 计算状态：是否临近到期 */
            isNearExpiry?: boolean;
            assignedTo?: components["schemas"]["UserBrief"];
            createdBy?: components["schemas"]["UserBrief"];
            /** Format: date-time */
            createdAt?: string;
        };
        RejectTaskRequest: {
            /** @example 碗没洗干净，请重新洗 */
            reason: string;
        };
        CancelTaskRequest: {
            /** @example 今天不在家吃饭 */
            reason?: string | null;
        };
        TaskTemplateItem: {
            /** Format: uuid */
            id?: string;
            /** @example 洗碗 */
            title?: string;
            description?: string | null;
            difficulty?: number;
            /** @enum {string} */
            suggestedRepeatRule?: "NONE" | "DAILY" | "WEEKLY";
            needsVerification?: boolean;
            /** @example 厨房 */
            category?: string;
            sortOrder?: number;
        };
        UploadResponse: {
            /** @example /uploads/2026/06/10/uuid-photo.jpg */
            url?: string;
            /** @example photo.jpg */
            originalName?: string;
            /** @example 204800 */
            size?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
